In [1]:
import pandas as pd

C:\Users\douth\anaconda3\Lib\site-packages\pandas\core\computation\expressions.py:22: UserWarning: Pandas requires version '2.10.2' or newer of 'numexpr' (version '2.8.7' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED
C:\Users\douth\anaconda3\Lib\site-packages\pandas\core\arrays\masked.py:56: UserWarning: Pandas requires version '1.4.2' or newer of 'bottleneck' (version '1.3.7' currently installed).
  from pandas.core import (

In [11]:
df=pd.read_csv(r"C:\Users\douth\Downloads\Flavors.csv")
df

,Flavor,Base Flavor,Liked,Flavor Rating,Texture Rating,Total Rating
0,Mint Chocolate Chip,Vanilla,Yes,10.0,8.0,18.0
1,Chocolate,Chocolate,Yes,8.8,7.6,16.6
2,Vanilla,Vanilla,No,4.7,5.0,9.7
3,Cookie Dough,Vanilla,Yes,6.9,6.5,13.4
4,Rocky Road,Chocolate,Yes,8.2,7.0,15.2
5,Pistachio,Vanilla,No,2.3,3.4,5.7
6,Cake Batter,Vanilla,Yes,6.5,6.0,12.5
7,Neapolitan,Vanilla,No,3.8,5.0,8.8
8,Chocolte Fudge Brownie,Chocolate,Yes,8.2,7.1,15.3

In [71]:
group_by_frame = df.groupby('Base Flavor')[['Flavor Rating', 'Texture Rating', 'Total Rating']]

In [73]:
group_by_frame.mean()

             Flavor Rating  Texture Rating  Total Rating
Base Flavor
Chocolate              8.4        7.233333         15.70
Vanilla                5.7        5.650000         11.35

In [75]:
group_by_frame.sum()

             Flavor Rating  Texture Rating  Total Rating
Base Flavor
Chocolate             25.2            21.7          47.1
Vanilla               34.2            33.9          68.1

In [81]:
group_by_frame.min()

             Flavor Rating  Texture Rating  Total Rating
Base Flavor
Chocolate              8.2             7.0          15.2
Vanilla                2.3             3.4           5.7

In [83]:
group_by_frame.max()

             Flavor Rating  Texture Rating  Total Rating
Base Flavor
Chocolate              8.8             7.6          16.6
Vanilla               10.0             8.0          18.0

In [85]:
group_by_frame.count()

             Flavor Rating  Texture Rating  Total Rating
Base Flavor
Chocolate                3               3             3
Vanilla                  6               6             6

In [95]:
df.groupby('Base Flavor').agg({
    'Flavor Rating': ['mean', 'count', 'sum'],
    'Texture Rating': ['mean', 'count', 'sum']
})

            Flavor Rating             Texture Rating
                     mean count   sum           mean count   sum
Base Flavor
Chocolate             8.4     3  25.2       7.233333     3  21.7
Vanilla               5.7     6  34.2       5.650000     6  33.9

In [99]:
df.groupby(['Base Flavor','Liked'])[['Flavor Rating','Texture Rating']].mean()

                   Flavor Rating  Texture Rating
Base Flavor Liked
Chocolate   Yes              8.4        7.233333
Vanilla     No               3.6        4.466667
            Yes              7.8        6.833333

In [101]:
df.groupby('Base Flavor','Liked').agg({
    'Flavor Rating': ['mean', 'count', 'sum'],
    'Texture Rating': ['mean', 'count', 'sum']
})

ValueError: level name Liked is not the name of the index